In [154]:
import pandas  as pd

In [155]:
dataset =pd.read_csv("insurance_pre.csv");

In [156]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [157]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [158]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [159]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [160]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [161]:
dependent=dataset[['charges']]

In [162]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [224]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor( n_estimators=100, criterion='poisson', max_features='log2')
regressor=regressor.fit(X_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [225]:
y_pred=regressor.predict(X_test)

In [226]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [227]:
r_score

0.8678598047737017

In [177]:
import pickle
filename="finalized_model_RandomForest_Assignment.sav"
pickle.dump(regressor,open(filename,'wb'))

In [80]:
loaded_model=pickle.load(open("finalized_model_RandomForest_Assignment.sav",'rb'))
result=loaded_model.predict([[30,25,2,0,1]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [81]:
result

array([18466.536504])